### ISSUE TITLE
Add to composer.json

### ISSUE THREAD

**Issue by quotidianus** [libre-informatique/SymfonyLibrinfoEmailBundle#4]
```bash
     "require": {
        ...
        "blast-project/utils-bundle": "dev-master",
        ...
     }
```

**Comment by FanchTheSystem** [comment]
please submit a pull request if it is still needed

**Comment by quotidianus** [comment]
My precedent pull request must be first accepted as it has some other changes on the file composer.json which is concerning.

**Comment by FanchTheSystem** [comment]
should be  "blast-project/utils-bundle": "^0.4"

**Comment by quotidianus** [comment]
Ok. Corrected in my repository. Do you want now a pull request for this or do I wait others corrections ?

**Comment by FanchTheSystem** [comment]
please submit a pull request if it is still needed

**Comment by FanchTheSystem** [comment]
https://github.com/libre-informatique/EmailBundle/commit/3c70bd3c60e14e7a3225585cce1b92f87d77047a
